# -*- coding: utf-8 -*-
"""Rekomendasi by KNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14SVghOPIz2F5SkQ-Qu26fL5A5GOmJWbk
"""

import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.neighbors import NearestNeighbors

df = pd.read_csv('/content/data.csv')

df.head()

movie = df.copy()
movie.isnull().sum()

#Load dan bersihkan data
movie = movie[movie['title'].notnull()]
movie = movie[movie['genres'].notnull()]
movie = movie.reset_index(drop=True)

#Vektorisasi genre
tfidf = TfidfVectorizer(stop_words='english')
tfidf_matrix = tfidf.fit_transform(movie['genres'])

#model KNN berdasarkan genre
model_knn_genre = NearestNeighbors(metric='cosine', algorithm='brute')
model_knn_genre.fit(tfidf_matrix)

def recommend_by_genre(title, n_recommendations=5):
    title_lower = title.lower()
    matches = movie[movie['title'].str.lower() == title_lower]

    if matches.empty:
        print("Judul tidak ditemukan.")
        return

    idx = matches.index[0]

    distances, indices = model_knn_genre.kneighbors(tfidf_matrix[idx], n_neighbors=n_recommendations + 1)

    print(f"\nRekomendasi berdasarkan genre untuk '{movie.loc[idx, 'title']}':")
    for i in range(1, len(indices[0])):
        rekom_idx = indices[0][i]
        print(f"- {movie.loc[rekom_idx, 'title']} (Jarak: {distances[0][i]:.4f})")

recommend_by_genre("Lucid")